name: fakensplash
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.1.0
  freezed_annotation: ^0.11.0
  auto_route: ^0.5.0
  font_awesome_flutter: ^8.8.1
  time: ^1.3.0
  rxdart: ^0.24.1
  dio: ^3.0.9
  retrofit: ^1.3.4
  get_it: ^4.0.2
  extended_nested_scroll_view: ^1.0.1
  tuple: ^1.0.3
  json_annotation: ^3.0.1
  provider: ^4.1.3
  intl: ^0.16.1
  url_launcher: ^5.4.10
  share: ^0.6.4+3
  wiredash: ^0.1.0
  gallery_saver: ^2.0.1
  oktoast: ^2.3.2
  wallpaper_manager: ^1.0.7
  flutter_cache_manager: ^1.1.3
  photo_view: ^0.9.2
  cached_network_image: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.5.0
  build_runner: ^1.10.0
  retrofit_generator: ^1.3.4
  freezed: ^0.11.0
  json_serializable: ^3.3.0

flutter:

  uses-material-design: true

scripts: derry.yaml
